- name: Install crontab
  package:
    name: "{{ cron_pkg }}"
    state: present

- name: Ensure cron directory exists
  file:
    path: "{{ cron_spool_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0700
  register: cron_spool_dir_exists

- name: Create crontab entries for dspace instances
  template:
    src: dspace_crontab.j2
    dest: "{{ cron_spool_dir }}/{{ dspace_service_user }}"
    owner: "{{ dspace_service_user }}"
    group: "{{ dspace_service_user }}"
    mode: 0600
  when: cron_spool_dir_exists